### PR TITLE
feat: add Hacktoberfest badge component

### PR DESCRIPTION
**Pull request by kala2**
Closes #

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dbartholomae** [comment]
Fixes #1

**Comment by dbartholomae** [comment]
Thanks! I've merged it and it will be released shortly :)

**Comment by kala2** [comment]
Could you please add the hacktoberfest-accepted label? It's for the hacktoberfest event!

**Comment by dbartholomae** [comment]
It should be enough that it is merged. Could you check the status you see for this PR on the Hacktoberfest page?

**Comment by kala2** [comment]
The rules for participating are changed a few days ago.

_Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted.
Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest._

more info: **https://hacktoberfest.digitalocean.com/details**

**Comment by dbartholomae** [comment]
Yes, I know. Here's your quote with my emphasis:

Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and **once they have been merged**, approved by a maintainer or labelled as hacktoberfest-accepted.
Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

**Pull request merged**
