### PR TITLE
feat: added_CLA_Assistant_Badge

### PR DESCRIPTION
**Pull request by anshdhinhgra47**
Closes #

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dbartholomae** [comment]
Hi @anshdhinhgra47! You will have to add tests, and also make sure that the Badge is linking somewhere. Happy to help if there are any questions.

**Comment by anshdhinhgra47** [comment]
Alright, I'll just work on it

**Comment by anshdhinhgra47** [comment]
I have to run the "npm test" command to add the tests right ?

**Comment by dbartholomae** [comment]
`npm test` will run the tests, but you will have to add the tests manually. Here's another PR for a badge that also contains the tests:
https://github.com/dbartholomae/jsx-readme/pull/21/files

**Comment by anshdhinhgra47** [comment]
I'll just look at it!

**Review by dbartholomae — APPROVED** [review]

**Pull request merged**
